version: '2'
services:
    soatcodingchallenge-app:
        image: soatcodingchallenge
            - soatcodingchallenge-mariadb:mariadb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/soatcodingchallenge
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    soatcodingchallenge-mariadb:
        extends:
            file: mariadb.yml
            service: soatcodingchallenge-mariadb
